accounts/urls.py
from django.urls import path
from .views import SignUpView
from . import views

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("accounts/profile/", views.user_posts, name="profile"),
    path('profile/edit/', views.edit_profile, name='edit'),
    path('user/<str:username>/', views.user_posts, name='user_posts'),
]

blogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('', views.display_random_posts, name='home'),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('posts/', include('posts.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='posts'),
    path('new_post/', views.create_post, name='create_post'),
    path('edit/<int:post_id>/', views.edit_post, name='edit_post'),
    # path('edit/<int:post_id>/edit/', views.edit_post, name='edit_post'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('delete/<int:post_id>/', views.delete_post, name='delete_post'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
    path('dislike/<int:post_id>/', views.dislike_post, name='dislike_post'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from .forms import CustomUserManager
from django.db import models


class CustomUser(AbstractUser):
    bio = models.TextField()
    location = models.CharField(max_length=255)
    email = models.EmailField(unique=True)

    # You can add more custom fields here

    def __str__(self):
        return self.username


class Meta:
    swappable = 'AUTH_USER_MODEL'


# Specify related_name for groups and user_permissions fields
CustomUser._meta.get_field(
    'groups').remote_field.related_name = 'customuser_set'
CustomUser._meta.get_field(
    'user_permissions').remote_field.related_name = 'customuser_set'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.models import BaseUserManager


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        return self.create_user(email, password, **extra_fields)


class CustomUserCreationForm(UserCreationForm):
    # Customize the form fields by overriding the fields attribute
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

        objects = CustomUserManager()


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views import generic
from posts.models import Post


def create_account(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # Redirect to the login page after successful user creation
            return redirect('login')
    else:
        form = CustomUserCreationForm()

    return render(request, 'create_account.html', {'form': form})


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"


def user_posts(request):
    if request.user.is_authenticated:
        user_id = request.user.id
        user_posts = Post.objects.filter(created_by_id=request.user)
        context = {'user_posts': user_posts}
        return render(request, "accounts/profile.html", context)
    else:
        return render(request, 'accounts/profile.html')


def edit_profile(request):
    user = request.user

    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        username = request.POST['username']

        user.first_name = first_name
        user.last_name = last_name
        user.email = email
        user.username = username
        user.save()

        # Redirect to the profile page after saving changes
        return redirect('profile')

    context = {'user': user}
    return render(request, 'accounts/edit_profile.html', context)

accounts/templates/accounts/edit_profile.html
{% extends 'blogProject/layout.html' %} {% load static %} {% block content %}
<html>
  <head>
    <title>Post details</title>
    <link rel="stylesheet" href="{% static 'blog/css/globals.css' %}" />
  </head>
  <body>
    <div class="edit-profile-container">
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="first_name">First Name:</label>
          <input
            type="text"
            id="first_name"
            name="first_name"
            value="{{ user.first_name }}"
          />
        </div>
        <div class="form-group">
          <label for="last_name">Last Name:</label>
          <input
            type="text"
            id="last_name"
            name="last_name"
            value="{{ user.last_name }}"
          />
        </div>
        <div class="form-group">
          <label for="username">Username:</label>
          <input
            type="text"
            id="username"
            name="username"
            value="{{ user.username }}"
          />
        </div>
        <div class="form-group">
          <label for="email">Email:</label>
          <input
            type="email"
            id="email"
            name="email"
            value="{{ user.email }}"
          />
        </div>
      </div>
        <button class="btn btn-primary w-15" type="submit">Save</button>
      </form>
    
  </body>
</html>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'blogProject/layout.html' %} {% block content %}
<html>
  <head>
    {% load static %} {% if user.is_authenticated %}
    <title>
      {% if user.first_name != "" %} {{ user.first_name }}'s profile {% elif
      user.username != "" %} {{ user.username }}'s profile {% else %} Hello user
      {% endif %}
    </title>
  </head>
  <script>
    const csrfToken = "{{ csrf_token }}"; // Add the CSRF token to the JavaScript code
  </script>
  <main>
    <body>
      <div class="profile-container">
        <div class="profile-top">
          <div class="profile-top-left">
            <img id="profile-picture" />
            {% if user.first_name != "" %}
            <h1 class="mb-3 h2">Hello {{ user.first_name }}</h1>
            {% elif user.username != "" %}
            <h1 class="mb-3 h2">Hello {{ user.username }}</h1>
            {% else %}
            <h1 class="mb-3 h2">Hello user</h1>
            {% endif %}
          </div>

          <div class="profile-top-right">
            <a href="{% url 'edit' %}">
              <button class="btn btn-primary w-15">Edit profile</button>
            </a>
            <a href="{% url 'logout' %}">
              <button class="btn btn-primary w-15">Log out</button>
            </a>
            <a href="{% url 'posts:create_post' %}">
              <button class="btn btn-primary w-15">New Post</button>
            </a>
          </div>
        </div>
        <div class="profile-bottom">
          <div class="profile-about-container">
            <h3>About info</h3>
            <div class="profile-about-info">
              <h5>Name</h5>
              <p>{{user.first_name}} {{user.last_name}}</p>
              <h5>Username</h5>
              <p>{{user.username}}</p>
              <h5>Sign-up date</h5>
              <p>{{user.date_joined}}</p>
              <h5>Email</h5>
              <p>{{user.email}}</p>
            </div>
          </div>
          <div class="profile-post-container">
            <h3>User posts</h3>
            <div class="profile-user-posts">
              <div class="row">
                {% if user_posts %} {% for post in user_posts %}
                <div class="col-md-12">
                  <div class="card mb-4">
                    <div class="card-body d-flex justify-content-between">
                      <div>
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text">{{ post.content }}</p>
                        <p class="card-text">
                          <small class="text-muted"
                            >Posted on {{ post.created_at }}</small
                          >
                        </p>
                      </div>
                      <div class="user-post-buttons">
                        <a
                          href="{% url 'posts:post_detail' post_id=post.id %}"
                          class="btn btn-primary w-15"
                          >View post</a
                        >
                        <a
                          href="{% url 'posts:edit_post' post_id=post.id %}"
                          class="btn btn-primary w-15"
                          >Edit post</a
                        >
                        <a
                          href="{% url 'posts:delete_post' post_id=post.id %}"
                          class="btn btn-danger delete-post"
                          data-post-id="{{ post.id }}"
                          onclick="confirmDelete(event)"
                          >Delete Post</a
                        >
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %} {% else %}
                <p>No posts by this user.</p>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        {% else %}
        <p>You are not logged in!</p>
        <p><a href="{% url 'login' %}">Log in</a></p>
      </div>
    </body>
  </main>
  {% endif %}
</html>
{% endblock %}