blogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('', views.display_random_posts, name='home'),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('posts/', include('posts.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='posts'),
    path('new_post/', views.create_post, name='create_post'),
    path('edit/<int:post_id>/', views.edit_post, name='edit_post'),
    # path('edit/<int:post_id>/edit/', views.edit_post, name='edit_post'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('delete/<int:post_id>/', views.delete_post, name='delete_post'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
    path('dislike/<int:post_id>/', views.dislike_post, name='dislike_post'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

LIKE_CHOICES = [
    ('like', 'Like'),
    ('dislike', 'Dislike'),
]


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    liked_users = models.ManyToManyField(
        User, related_name='liked_posts', blank=True)
    disliked_users = models.ManyToManyField(
        User, related_name='disliked_posts', blank=True)

    def like_count(self):
        return self.liked_users.count()

    def dislike_count(self):
        return self.disliked_users.count()

    def __str__(self):
        return self.title


class LikeDislike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    # True for like, False for dislike
    like = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        # Ensure a user can like/dislike a post only once
        unique_together = ['user', 'post']

posts/forms.py
from django import forms
from .models import Post


class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

posts/views.py
from .models import Post
from .forms import PostForm
from .forms import NewPostForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
import random


def post_list(request):
    all_posts = Post.objects.all()
    paginator = Paginator(all_posts, 6)
    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)
    return render(request, 'posts/post_list.html', {'posts': posts})


@login_required
def create_post(request):
    if request.method == 'POST':
        form = NewPostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.created_by_id = request.user.id
            post.save()
            return redirect("posts:posts")
    else:
        form = NewPostForm()

    return render(request, 'posts/new_post.html', {'form': form})


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'posts/post_detail.html', {'post': post})


def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        user_posts = Post.objects.filter(created_by_id=request.user)
        context = {'user_posts': user_posts}

        if form.is_valid():
            form.save()
            return render(request, "accounts/profile.html", context)
    else:
        form = PostForm(instance=post)

    context = {'form': form}
    return render(request, 'posts/edit_post.html', context)


def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    user_posts = Post.objects.filter(created_by_id=request.user)
    context = {'user_posts': user_posts}
    return render(request, 'accounts/profile.html', context)


def like_post(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(Post, id=post_id)
        user = request.user  # Assuming you have authenticated users
        print('success')

        if user in post.liked_users.all():
            post.liked_users.remove(user)
        else:
            post.liked_users.add(user)
            post.disliked_users.remove(user)

        return JsonResponse({'like_count': post.like_count()})
    else:
        return JsonResponse({'error': 'Invalid request'})


def dislike_post(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(Post, id=post_id)
        user = request.user  # Assuming you have authenticated users

        if user in post.disliked_users.all():
            post.disliked_users.remove(user)
        else:
            post.disliked_users.add(user)
            post.liked_users.remove(user)

        return JsonResponse({'dislike_count': post.dislike_count()})
    else:
        return JsonResponse({'error': 'Invalid request'})


def display_random_posts(request):
    # Get all the posts
    all_posts = Post.objects.all()

    # Randomly select 6 posts
    selected_posts = random.sample(list(all_posts), 6)

    # Pass the selected posts to the template context
    return render(request, 'home.html', {'selected_posts': selected_posts})

posts/templates/posts/card_layout.html
{% load static%}
<link
      rel="stylesheet"
      href="{% static 'fontawesome_5/css/all.min.css' %}"
    />
{% for post in posts %}
<div class="col-md-6">
  <div class="card mb-4">
    <div class="card-body">
      <h5 class="card-title">{{ post.title }}</h5>
      <p class="card-text">{{ post.content }}</p>
      <p class="card-text">
        <small class="text-muted">Posted on {{ post.created_at }}</small>
      </p>
      <div class="like-dislike-buttons">
        <form method="post" action="{% url 'posts:like_post' post_id=post.id %}">
          {% csrf_token %}
          <label>
            <input type="radio"
              name="choice_{{ post.id }}"
              class="like-button"
              data-post-id="{{ post.id }}"
              value="like"
              {% if post.user_choice == 'like' %}
              checked
              {% endif %}
            />
            <span class="button-label" {% if post.user_choice == 'like' %} selected {% endif %} ><i class="fa fa-thumbs-up"></i> {{post.like_count}}</span>
          </label>
        </form>
      
        <form method="post" action="{% url 'posts:like_post' post_id=post.id %}">
          {% csrf_token %}
          <label>
            <input type="radio"
              name="choice_{{ post.id }}"
              class="dislike-button"
              data-post-id="{{ post.id }}"
              value="dislike"
              {% if post.user_choice == 'dislike' %}
              checked
              {% endif %}
            />
            <span class="button-label" 
            {% if post.user_choice == 'dislike' %} selected {% endif %} ><i class="fa fa-thumbs-down"></i> {{post.dislike_count}}</span>
          </label>
        </form>
      </div>
      
    </div>
  </div>
</div>

{% endfor %}

posts/templates/posts/edit_post.html
{% extends 'blogProject/layout.html' %} {% load static %} {% block content %}
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Edit Post</title>
    <link rel="stylesheet" href="{% static 'blog/css/globals.css' %}" />
  </head>
  <div class="container">
    <h1 class="mt-4 mb-4">Edit Post</h1>

    <form action="{% url 'posts:create_post' %}" method="POST">
      {% csrf_token %}
      <div class="mb-3">
        <label for="title" >Title</label>
        <input
          type="text"
          class="form-control"
          id="title"
          name="title"
          value="{{ form.title.value }}"
          required
        />
      </div>
      <div class="mb-3">
        <label for="content" class="form-label">Content</label>
        <textarea
          class="form-control"
          id="content"
          name="content"
          rows="5"
          required
        >{{ form.content.value }}</textarea>
      </div>
      <button type="submit" class="btn btn-primary w-15">Update Post</button>
    </form>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}

posts/templates/posts/new_post.html
<!DOCTYPE html>
{% extends 'blogProject/layout.html' %} {% load static %} {% block content %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>New Post</title>
    <link rel="stylesheet" href="{% static 'blog/css/globals.css' %}" />
  </head>
  <body>
    <div class="container">
      <h1 class="mt-4 mb-4">New Post</h1>

      <form action="{% url 'posts:create_post' %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
          <label for="title">Title</label>
          <input
            type="text"
            class="form-control"
            id="title"
            name="title"
            required
          />
        </div>
        <div class="mb-3">
          <label for="content" class="form-label">Content</label>
          <textarea
            class="form-control"
            id="content"
            name="content"
            rows="5"
            required
          ></textarea>
        </div>
        <button type="submit" class="btn btn-primary w-15">Create Post</button>
      </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'blogProject/layout.html' %} {% load static %} {% block content %}
<html>
  <head>
    <title>Post details</title>
    <link rel="stylesheet" href="{% static 'blog/css/globals.css' %}" />
  </head>
  <body>
    <div class="post-details-container">
      <h2>Title: {{ post.title }}</h2>
      <p>Content: {{ post.content }}</p>
      <p>Author: {{ post.created_by.username }}</p>
      <p>Created at: {{ post.created_at }}</p>
      <p>Updated at: {{ post.updated_at }}</p>
      <button id="backButton" class="btn btn-primary w-15">Back</button>
    </div>
  </body>
  <script>
    document
      .getElementById("backButton")
      .addEventListener("click", function () {
        history.back();
      });
  </script>
</html>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'blogProject/layout.html' %}
{% block content %}
  <div class="container">
    <h1 class="mt-4 mb-4">Blog Posts</h1>

    <div class="row">
      {% include 'posts/card_layout.html' with posts=posts %} 
    </div>
    
    <nav aria-label="Page navigation">
      <ul class="pagination">
        {% if posts.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a></li>
        {% endif %}

        {% for i in posts.paginator.page_range %}
        {% if posts.number == i %}
        <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}

        {% if posts.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}">Next</a></li>
        {% endif %}
      </ul>
    </nav>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function (){" "}
    {$(".like-button, .dislike-button").on("click", function () {
      const postID = $(this).data("post-id");
      const choice = $(this).val();
  
      $.ajax({
        type: "POST",
        url: "/posts/like/" + postID + "/", // Replace '/like_post/' with your actual URL pattern
        data: {
          csrfmiddlewaretoken: "{{ csrf_token }}",
          post_id: postID,
          choice: choice,
        },
        success: function (response) {
          if (choice === "like") {
            // Handle the 'like' response here (e.g., update like count)
            $("#like-count-" + postID).text(response.like_count);
          } else if (choice === "dislike") {
            // Handle the 'dislike' response here (e.g., update dislike count)
            $("#dislike-count-" + postID).text(response.dislike_count);
          }
        },
        error: function (error) {
          console.log(error);
        },
      });
    })}
    )
  </script>
  
{% endblock %}